### ISSUE TITLE
Issue with Node.js SDK

### ISSUE THREAD

**Issue by gajus** [persona-id/inquiry-android-2#3]
Hey folks, I cannot find your repo for https://www.npmjs.com/package/persona

CC @malavbhavsar @neelb @RickCSong

TLDR can you please patch your Node.js SDK to export these types.

```diff
diff --git a/dist/persona.d.ts b/dist/persona.d.ts
index af5178c42de32a67be2b9e5883dbbc3ae10c3821..13753c289c02558a48406df063ab36c70e7b5412 100644
--- a/dist/persona.d.ts
+++ b/dist/persona.d.ts
@@ -11,3 +11,5 @@ declare const _default: {
 };
 export default _default;
 export { Client, Inquiry };
+export { type InquiryError } from './lib/interfaces';
+export { type InquiryOptions } from './lib/interfaces';
```

We now have to locally patch the SDK to get around it.

**Comment by timhwang21** [comment]
Hi @gajus, thanks for opening the issue. Our SDK is not open source, which is why you couldn't find the repo. 

Can you share the version you are on? `InquiryOptions` should be exposed as an export named `ClientOptions`. We can expose `InquiryError` as well, but based on the diff you shared you may need to do a major version bump. It shouldn't be too involved, but if it is and you want to avoid patching the package, you can extract the type from the arguments of `ClientOptions['onError']`.

In general, you'll get a faster response by going through the [Persona Dashboard's contact page](https://app.withpersona.com/dashboard/contact-us), or talking to your CSM if you are a managed customer. We don't actively monitor GitHub for support tickets; I just happened to see this one. 

I'm going to close this issue, but please feel free to follow up if you have other questions.

**Comment by timhwang21** [comment]
@gajus `InquiryError` has been released in [v5.1.1](https://www.npmjs.com/package/persona/v/5.1.1), please take a look.

**Comment by gajus** [comment]
Thank you

**Comment by gajus** [comment]
p.s. My suggestion would be to create an empty GitHub repository and call it `persona-javascript-sdk`. Just so people like me could easily find it and raise issues. Otherwise you are missing out on valuable feedback.

**Comment by gajus** [comment]
@timhwang21 Can you please also re-export `default` as `Inquiry` named export?

The default export is causing problems with ESM.

**Comment by timhwang21** [comment]
@gajus the default exports are also exported as named exports. This is our entrypoint from our latest release:

```typescript
import Client from './lib/Client';
import { setupIframe } from './lib/setupIframe';
import { setupEvents } from './lib/setupEvents';
import type {
  InquiryOptions,
  InquiryError as _InquiryError,
  Event as _Event,
} from './lib/interfaces';

export type ClientOptions = InquiryOptions;
export type InquiryError = _InquiryError;
export type Event = _Event;

export default { Client, setupIframe, setupEvents };

// Support named imports
// eg: import { Client } from 'persona'
export { Client, setupIframe, setupEvents };
```

Does this solve your problem? Thanks!

**Comment by gajus** [comment]
Confused. Maybe something else changed.

```ts
import {
  type ClientOptions,
  Inquiry,
  type InquiryError,
  type Event as PersonaEvent,
} from 'persona';
```

This was our import before. Seems like `Inquiry` is gone?

**Comment by gajus** [comment]
Never mind. Just found the changelog.

https://docs.withpersona.com/docs/embedded-flow-changelog#-breaking-changes

Once again.. having this in GitHub would feel more natural.

**Comment by timhwang21** [comment]
Acknowledged -- we have discussed open sourcing our SDKs and centralizing more on Github, but it's not an immediate priority and has some concerns we need to work through (with one major issue being how easy it is for users to accidentally share sensitive information in a public forum).

**Comment by gajus** [comment]
Well... `persona-react` has the same issue, i.e. default import is not working with ESM.

```
JSX element type 'Inquiry' does not have any construct or call signatures.ts(2604)
'Inquiry' cannot be used as a JSX component.
  Its type 'typeof import("/Users/x/Developer/contra/gaia/node_modules/.pnpm/persona-react@5.1.0_react@18.3.1/node_modules/persona-react/dist/persona-react")' is not a valid JSX element type.ts(2786)
```

We can patch this locally with `pnpm patch persona-react`, but ideally you'd provide named export of the component.

**Comment by gajus** [comment]
> Acknowledged -- we have discussed open sourcing our SDKs and centralizing more on Github, but it's not an immediate priority and has some concerns we need to work through (with one major issue being how easy it is for users to accidentally share sensitive information in a public forum).

I am not advocating you open-sourcing it. Just create an empty repo that people discover where they can raise issues and such.

**Comment by timhwang21** [comment]
> Well... persona-react has the same issue, i.e. default import is not working with ESM.

Ack -- thanks for raising. I'm cutting a release for `persona-react@5.1.1` that will resolve this issue, that should be available imminently.

edit: available here now: https://www.npmjs.com/package/persona-react/v/5.1.1

> I am not advocating you open-sourcing it. Just create an empty repo that people discover where they can raise issues and such.

We've made this to redirect folks to our official support channels, but as of now we're not allowing public raising of issues for the aforementioned reasons: https://github.com/persona-id/persona-inquiry-sdk-public/
